org: piktekk
app: demo-linh-tinh
service: dms-jira

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_URI: ${env:MONGODB_URI}
    JIRA_API_BASE: ${env:JIRA_API_BASE}
    JIRA_API_BASE_V1: ${env:JIRA_API_BASE_V1}
    JIRA_EMAIL: ${env:JIRA_EMAIL}
    JIRA_API_TOKEN: ${env:JIRA_API_TOKEN}

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline  # For local testing

custom:
  serverless-offline:
    httpPort: 3001
